"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class command(object):
    __slots__ = ["joint_position", "joint_velocity", "joint_kp", "joint_kd", "torque_feedforward"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[12], [12], [12], [12], [12]]

    def __init__(self):
        self.joint_position = [ 0.0 for dim0 in range(12) ]
        self.joint_velocity = [ 0.0 for dim0 in range(12) ]
        self.joint_kp = [ 0.0 for dim0 in range(12) ]
        self.joint_kd = [ 0.0 for dim0 in range(12) ]
        self.torque_feedforward = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.joint_position[:12]))
        buf.write(struct.pack('>12f', *self.joint_velocity[:12]))
        buf.write(struct.pack('>12f', *self.joint_kp[:12]))
        buf.write(struct.pack('>12f', *self.joint_kd[:12]))
        buf.write(struct.pack('>12f', *self.torque_feedforward[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = command()
        self.joint_position = struct.unpack('>12f', buf.read(48))
        self.joint_velocity = struct.unpack('>12f', buf.read(48))
        self.joint_kp = struct.unpack('>12f', buf.read(48))
        self.joint_kd = struct.unpack('>12f', buf.read(48))
        self.torque_feedforward = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if command in parents: return 0
        tmphash = (0x9105074b4f58912d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if command._packed_fingerprint is None:
            command._packed_fingerprint = struct.pack(">Q", command._get_hash_recursive([]))
        return command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", command._get_packed_fingerprint())[0]

