<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:include filename="$(find laikago_description)/xacro/transmission.xacro"/> -->

    <xacro:macro name="leg_front" params="name mirror mirror_dae front_hind front_hind_dae *origin">

        <joint name="${name}_1_joint" type="revolute">
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_1"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}"
                   lower="${hip_min*PI/180.0}" upper="${hip_max*PI/180.0}"/>
        </joint>

        <link name="${name}_1">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_1.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_1.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${J1Z+J1+J2Z}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_2_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 ${f2_y*mirror} 0"/>
            <parent link="${name}_1"/>
            <child link="${name}_2"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"
                       lower="${thigh_min*PI/180.0}" upper="${thigh_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}"
                       lower="${-thigh_max*PI/180.0}" upper="${-thigh_min*PI/180.0}"/>
            </xacro:if>
        </joint>

        <link name="${name}_2">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_2.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_2.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${J2+J3Z}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_3_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${-f3_z}"/>
            <parent link="${name}_2"/>
            <child link="${name}_3"/>>
        </joint>

        <link name="${name}_3">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_3.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_3.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${-f4_z/2}"/>
                <mass value="${J3+L34}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_4_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-f4_z}"/>
            <parent link="${name}_3"/>
            <child link="${name}_4"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min*PI/180.0}"
                   upper="${calf_max*PI/180.0}"/>
        </joint>

        <link name="${name}_4">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_4.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_4.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${-f5_z/2}"/>
                <mass value="${J4+L45}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_5_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${-f5_x} ${-f5_y*mirror} ${-f5_z}"/>
            <parent link="${name}_4"/>
            <child link="${name}_5"/>
        </joint>

        <link name="${name}_5">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_5.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_5.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${J5+J5Z}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_6_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${f6_z}"/>
            <parent link="${name}_5"/>
            <child link="${name}_6"/>
        </joint>

        <link name="${name}_6">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_6.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_6.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${J6Z+J6+hand}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_foot_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${-f_foot_z}"/>
            <parent link="${name}_4"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${foot_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <!-- <xacro:leg_transmission name="${name}"/> -->
    </xacro:macro>
</robot>
