<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:include filename="$(find laikago_description)/xacro/transmission.xacro"/> -->

    <xacro:macro name="leg_hind" params="name mirror mirror_dae front_hind front_hind_dae *origin">

        <joint name="${name}_1_joint" type="revolute">
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_1"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}"
                   lower="${hip_min*PI/180.0}" upper="${hip_max*PI/180.0}"/>
        </joint>

        <link name="${name}_1">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_a.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_a.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${hj_1_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_2_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 ${h2_y*mirror} 0"/>
            <parent link="${name}_1"/>
            <child link="${name}_2"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"
                       lower="${thigh_min*PI/180.0}" upper="${thigh_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"
                       lower="${-thigh_max*PI/180.0}" upper="${-thigh_min*PI/180.0}"/>
            </xacro:if>
        </joint>

        <link name="${name}_2">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_h.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_h.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${-h3_z/2}"/>
                <mass value="${hj_2_mass+hl_2_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_3_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-h3_z}"/>
            <parent link="${name}_2"/>
            <child link="${name}_3"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min*PI/180.0}"
                   upper="${calf_max*PI/180.0}"/>
        </joint>

        <link name="${name}_3">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_k.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="../meshes/${name}_k.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${-h5_z/2}"/>
                <mass value="${hj_3_mass+hl_3_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_4_continuous" type="fixed">
            <origin rpy="0 0 0" xyz="${-h4_x} ${h4_y*mirror} ${-h4_z}"/>
            <parent link="${name}_3"/>
            <child link="${name}_4"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}"/>
        </joint>

        <link name="${name}_4">
            <visual>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="../meshes/${name}_kw.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="../meshes/${name}_kw.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${hj_4_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="2e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_5_continuous" type="fixed">
            <origin rpy="0 0 0" xyz="${-h5_x} ${h5_y*mirror} ${-h5_z}"/>
            <parent link="${name}_3"/>
            <child link="${name}_5"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}"/>
        </joint>

        <link name="${name}_5">
            <visual>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="../meshes/${name}_fw.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="../meshes/${name}_fw.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${hj_5_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="2e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <joint name="${name}_foot_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${-wheel_radius}"/>
            <parent link="${name}_5"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${foot_mass}"/>
                <inertia
                        ixx="1e-3" ixy="0.0" ixz="0.0"
                        iyy="1e-3" iyz="0.0"
                        izz="1e-3"/>
            </inertial>
        </link>

        <!-- <xacro:leg_transmission name="${name}"/> -->
    </xacro:macro>
</robot>
